# Generated by Django 4.1.7 on 2023-03-31 19:43

import cws2.models.base
import cws2.models.user
import cws2.validators
from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cws2", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        verbose_name="Public status",
                        help_text=(
                            "Does everyone have an implicit read permission for this"
                            " resource?"
                        ),
                    ),
                ),
                (
                    "is_shared",
                    models.BooleanField(
                        default=False,
                        verbose_name="Sharing status",
                        help_text=(
                            "Are there specific user and group permissions set for"
                            " this resource?"
                        ),
                    ),
                ),
                ("uuid", models.CharField(db_index=True, max_length=22, unique=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="This is the name of your language, in English.",
                        max_length=64,
                        verbose_name="Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text=(
                            "This is like a username for your language, appearing in"
                            " your language page's URL. You may not have more than one"
                            " language with the same identifier."
                        ),
                        max_length=64,
                        unique=True,
                        verbose_name="Identifier",
                    ),
                ),
                (
                    "endonym",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text=(
                            "This is the name of your language, in your language."
                            " Don't worry if you don't know this yet - you can leave"
                            " this field blank."
                        ),
                        max_length=128,
                        verbose_name="Endonym",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text=(
                            "An abbreviation or ISO-style code for this language, if"
                            " you have one. This is purely cosmetic."
                        ),
                        max_length=6,
                        verbose_name="Language code",
                    ),
                ),
                (
                    "language_type",
                    models.CharField(
                        choices=[
                            ("NSP", "Not specified"),
                            ("APR", "A priori"),
                            ("APS", "A posteriori"),
                            ("ART", "Artistic language (artlang)"),
                            ("ENG", "Engineered language (englang)"),
                            ("IAL", "International auxiliary language (IAL)"),
                            ("LOG", "Logical language (loglang)"),
                            ("SGN", "Signed language"),
                            ("PRO", "Common ancestor language (proto-language)"),
                            ("PID", "Pidgin"),
                            ("CRE", "Creole"),
                            ("JOK", "Joke language"),
                            ("MIX", "Mixed"),
                            ("OTH", "Other"),
                        ],
                        default="NSP",
                        help_text=(
                            "Select the language type that best represents your"
                            " language."
                        ),
                        max_length=3,
                        verbose_name="Language type",
                    ),
                ),
                (
                    "language_status",
                    models.CharField(
                        choices=[
                            ("1", "New"),
                            ("2", "Progressing"),
                            ("3", "Functional"),
                            ("4", "Complete"),
                            ("X", "Abandoned"),
                            ("H", "On hold"),
                        ],
                        default="1",
                        help_text="What stage of development is your language at?",
                        max_length=1,
                        verbose_name="Language status",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text=(
                            "This is a brief summary of your language that will appear"
                            " on its page. You can write more specific articles about"
                            " the language later on."
                        ),
                        verbose_name="Summary",
                    ),
                ),
                (
                    "is_natural",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text=(
                            "Is this a natural language, rather than a constructed"
                            " language?"
                        ),
                        verbose_name="Natural language status",
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="archived_by_user_id",
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archived_%(class)ss+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by_user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owned_by",
                    models.ForeignKey(
                        db_column="owned_by_user_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by_user_id",
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)ss+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=(cws2.models.base.AutoSlugMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name="language",
            constraint=models.UniqueConstraint(
                fields=("owned_by", "slug"), name="cws2_language_unique_owner_slug"
            ),
        ),
    ]
