# Generated by Django 4.1.7 on 2023-03-25 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cws2", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    django_extensions.db.fields.ShortUUIDField(
                        blank=True, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="This is the name of your language, in English.",
                        max_length=64,
                        verbose_name="Name",
                    ),
                ),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        help_text=(
                            "This is like a username for your language, appearing in"
                            " your language page's URL. You may not have more than one"
                            " language with the same identifier."
                        ),
                        max_length=64,
                        populate_from="name",
                        verbose_name="Identifier",
                    ),
                ),
                (
                    "endonym",
                    models.CharField(
                        blank=True,
                        help_text=(
                            "This is the name of your language, in your language."
                            " Don't worry if you don't know this yet - you can leave"
                            " this field blank."
                        ),
                        max_length=128,
                        verbose_name="Endonym",
                    ),
                ),
                (
                    "language_type",
                    models.CharField(
                        choices=[
                            ("NSP", "Not specified"),
                            ("APR", "A priori"),
                            ("APS", "A posteriori"),
                            ("ART", "Artistic language (artlang)"),
                            ("ENG", "Engineered language (englang)"),
                            ("IAL", "International auxiliary language (IAL)"),
                            ("LOG", "Logical language (loglang)"),
                            ("SGN", "Signed language"),
                            ("PRO", "Common ancestor language (proto-language)"),
                            ("PID", "Pidgin"),
                            ("CRE", "Creole"),
                            ("JOK", "Joke language"),
                            ("MIX", "Mixed"),
                            ("OTH", "Other"),
                        ],
                        default="NSP",
                        help_text=(
                            "Select the language type that best represents your"
                            " language."
                        ),
                        max_length=16,
                        verbose_name="Language type",
                    ),
                ),
                (
                    "language_status",
                    models.CharField(
                        choices=[
                            ("1", "New"),
                            ("2", "Progressing"),
                            ("3", "Functional"),
                            ("4", "Complete"),
                            ("X", "Abandoned"),
                            ("H", "On hold"),
                        ],
                        default="1",
                        help_text="What stage of development is your language at?",
                        max_length=16,
                        verbose_name="Language status",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text=(
                            "This is a brief summary of your language that will appear"
                            " on its page. You can write more specific articles about"
                            " the language later on."
                        ),
                        verbose_name="Summary",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="languages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("created_by", "slug")},
            },
        ),
    ]
