# Generated by Django 4.1.7 on 2023-03-31 16:05

from django.db import migrations
import shortuuid

from cws2.constants import GroupAccessType


def add_groups_bots(apps, schema_editor):
    User = apps.get_model("cws2", "User")
    Group = apps.get_model("cws2", "Group")
    GroupMembership = apps.get_model("cws2", "GroupMembership")
    conlanger = Group.objects.create(
        name="Conlanger",
        uuid=shortuuid.uuid(),
        slug="conlanger",
        icon="✱",
        icon_colour_bg="#009999",
        icon_colour_fg="#FFFFFF",
        access_type=GroupAccessType.SYSTEM,
        is_hidden=False,
        is_everyone=True,
    )
    staff = Group.objects.create(
        name="High Council of CWS",
        uuid=shortuuid.uuid(),
        slug="staff",
        icon="✱",
        icon_colour_bg="#338833",
        icon_colour_fg="#FFFFFF",
        access_type=GroupAccessType.SYSTEM,
        is_hidden=False,
        is_everyone=False,
    )
    sheep = User.objects.create(
        username="sheep",
        uuid=shortuuid.uuid(),
        email="conworkshop@gmail.com",
        display_name="Admin Sheep",
        is_bot=True,
    )
    GroupMembership.objects.create(
        group=conlanger,
        user=sheep,
        invited_by=sheep,
    )
    GroupMembership.objects.create(
        group=staff,
        user=sheep,
        invited_by=sheep,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("cws2", "0002_language"),
    ]

    operations = [
        migrations.RunPython(add_groups_bots, reverse_code=migrations.RunPython.noop),
    ]
