# Generated by Django 4.1.7 on 2023-03-31 19:43

import cws2.models.base
import cws2.models.user
import cws2.validators
from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cws2", "0003_add_groups_bots"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhonoSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        verbose_name="Public status",
                        help_text=(
                            "Does everyone have an implicit read permission for this"
                            " resource?"
                        ),
                    ),
                ),
                (
                    "is_shared",
                    models.BooleanField(
                        default=False,
                        verbose_name="Sharing status",
                        help_text=(
                            "Are there specific user and group permissions set for"
                            " this resource?"
                        ),
                    ),
                ),
                ("uuid", models.CharField(max_length=22, unique=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="This is the name of the Phono System.",
                        max_length=64,
                        verbose_name="Name",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("D", "Draft"),
                            ("P", "Published"),
                        ],
                        default="D",
                        help_text="Release status of this Phono System.",
                        max_length=1,
                        verbose_name="Status",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text=(
                            "A brief summary of the Phono System."
                        ),
                        verbose_name="Summary",
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="archived_by_user_id",
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archived_%(class)ss+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by_user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owned_by",
                    models.ForeignKey(
                        db_column="owned_by_user_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by_user_id",
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)ss+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=(cws2.models.base.UUIDModel,
                   cws2.models.base.OwnableModel, models.Model),
        ),
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("uuid", models.CharField(max_length=22, unique=True)),
                (
                    "phono_system",
                    models.ForeignKey(
                        db_column="phono_system_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phono_system",
                        to="PhonoSystem",
                    ),
                ),
                (
                    "glyph",
                    models.CharField(
                        help_text="Glyph representation of this Phone.",
                        max_length=12,
                        verbose_name="X-Sampa",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="This is the name this Phone.",
                        max_length=64,
                        verbose_name="Name",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("C", "Consonant"),
                            ("V", "Vowel"),
                            ("Q", "Quality"),
                            ("U", "Uncategorized"),
                        ],
                        help_text="Category for this Phone.",
                        max_length=1,
                        verbose_name="Category",
                    ),
                ),
                (
                    "ipa",
                    models.CharField(
                        help_text="IPA phonetic representation of this Phone.",
                        max_length=12,
                        verbose_name="IPA",
                    ),
                ),
                (
                    "xsampa",
                    models.CharField(
                        help_text="X-Sampa phonetic representation of this Phone.",
                        max_length=12,
                        verbose_name="X-Sampa",
                    ),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=32),
                        blank=True,
                        default=list,
                        help_text="Tags associated with this Phone.",
                        size=None,
                        verbose_name="Tags",
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="archived_by_user_id",
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archived_%(class)ss+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by_user_id",
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by_user_id",
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)ss+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=(cws2.models.base.UUIDModel,
                   cws2.models.base.OwnableModel, models.Model),
        ),
        migrations.AddConstraint(
            model_name="phone",
            constraint=models.UniqueConstraint(
                fields=("phono_system_id", "glyph"), name="cws2_phone_unique_phono_system_glyph"
            ),
        ),
    ]
