# Generated by Django 4.1.7 on 2023-03-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cws2", "0003_language_archived_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email_confirmed",
        ),
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="preferred_name",
        ),
        migrations.AddField(
            model_name="user",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text=(
                    "This name will appear instead of your username in some places on"
                    " the site, if set."
                ),
                max_length=64,
                verbose_name="Display name",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_bot",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "If true, this user will be considered a staff-run bot account and"
                    " will not be able to be logged in to."
                ),
                verbose_name="Bot status",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
