# Generated by Django 4.1.7 on 2023-03-27 16:48

from django.db import migrations


def add_admin_sheep_bot(apps, schema_editor):
    User = apps.get_model("cws2", "User")
    User.objects.create_user("sheep", email="conworkshop@gmail.com", is_bot=True)


def remove_admin_sheep_bot(apps, schema_editor):
    User = apps.get_model("cws2", "User")
    User.objects.get(username="sheep").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("cws2", "0004_remove_user_email_confirmed_remove_user_first_name_and_more"),
    ]

    operations = [
        migrations.RunPython(
            add_admin_sheep_bot,
            reverse_code=remove_admin_sheep_bot,
        )
    ]
