# Generated by Django 4.1.7 on 2023-03-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cws2", "0006_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_seen_at",
            field=models.DateTimeField(
                blank=True,
                help_text="The last time this user accessed the site.",
                null=True,
                verbose_name="Last seen at",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_seen_ip",
            field=models.CharField(
                blank=True,
                help_text="The last IP address this user used to log in.",
                max_length=48,
                verbose_name="Last seen IP",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_seen_route",
            field=models.CharField(
                blank=True,
                help_text="The route name of the last page this user accessed.",
                max_length=64,
                verbose_name="Last seen route",
            ),
        ),
    ]
