# Generated by Django 4.2.3 on 2023-10-10 14:00

from django.db import migrations, models

import cws2.models.language


class Migration(migrations.Migration):
    dependencies = [
        ("cws2", "0006_dialect_dialect_cws2_dialect_language_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="language_flag",
            field=models.ImageField(
                blank=True,
                help_text="An optional flag image that represents your language or the place it's spoken. Common flag ratios are recommended, such as 1:2, 2:3 or 3:5 (height to width). The image must be at least 100px wide and 50px high.",
                upload_to=cws2.models.language.language_flag_path,
                verbose_name="Language flag",
            ),
        ),
    ]
