# Generated by Django 4.2.3 on 2023-10-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cws2", "0010_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="An optional, brief overview on what this group is all about.",
                verbose_name="Description",
            ),
        ),
    ]
