# Generated by Django 5.0.3 on 2024-03-28 19:06

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cws2", "0013_alter_worddefinition_register"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="uuid",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None,
                db_index=True,
                help_text="The unique ID that identifies this word.",
                length=22,
                max_length=22,
                prefix="",
                unique=True,
                verbose_name="UUID",
            ),
        ),
    ]
