# Generated by Django 5.1.3 on 2024-11-18 23:40

import cws2.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cws2', '0015_translationtemplate_translation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='An optional picture to show up on your profile and across the site.', upload_to=cws2.models.user.user_avatar_filename, verbose_name='Avatar'),
        ),
    ]
