# Generated by Django 5.1.3 on 2024-11-22 11:29

from django.db import migrations, models


def migrate_profile_fields_to_user(apps, _):
    User = apps.get_model("cws2", "User")
    fields = ("bio", "location", "pronouns")
    for user in User.objects.all():
        if not hasattr(user, "profile"):
            continue
        profile = user.profile
        for field in fields:
            setattr(user, field, getattr(profile, field))
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cws2', '0016_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Write something about yourself! This will appear on your profile page.', verbose_name='About me'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, help_text='Where in the world are you?', max_length=64, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='user',
            name='pronouns',
            field=models.CharField(blank=True, help_text='What pronouns should people use when referring to you?', max_length=64, verbose_name='Pronouns'),
        ),
        migrations.RunPython(
            migrate_profile_fields_to_user,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
