# Generated by Django 5.1.3 on 2024-11-29 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cws2', '0017_user_bio_user_location_user_pronouns_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='What should this board be called? This will appear in the boards page.', max_length=64, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, help_text="This is a unique board identifier that will appear in the board's URL.", max_length=64, verbose_name='Identifier')),
                ('archived_by', models.ForeignKey(blank=True, db_column='archived_by_user_id', db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_%(class)ss+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(db_column='created_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boards', to='cws2.group')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_user_id', db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.CharField(db_index=True, max_length=22, unique=True)),
                ('title', models.CharField(help_text='What should this thread be titled? Try and summarize what the conversation is about, but keep it short.', max_length=64, verbose_name='Title')),
                ('is_pinned', models.BooleanField(default=False)),
                ('archived_by', models.ForeignKey(blank=True, db_column='archived_by_user_id', db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_%(class)ss+', to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='cws2.board')),
                ('created_by', models.ForeignKey(db_column='created_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_user_id', db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.CharField(db_index=True, max_length=22, unique=True)),
                ('message', models.TextField(help_text='What do you want to say? Remember, this is public: be courteous.', verbose_name='Message')),
                ('archived_by', models.ForeignKey(blank=True, db_column='archived_by_user_id', db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_%(class)ss+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(db_column='created_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_user_id', db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss+', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='cws2.thread')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='board',
            constraint=models.UniqueConstraint(fields=('group', 'slug'), name='cws2_board_unique_group_slug'),
        ),
    ]
