# Generated by Django 5.1.3 on 2024-11-29 18:42

from django.db import migrations


BOARDS_TO_CREATE = (
    ("conlanger", "Announcements", "announcements"),
    ("conlanger", "Conlang Games", "games"),
    ("conlanger", "Conlang Topics", "topics"),
    ("conlanger", "Conlangs Threads", "threads"),
    ("conlanger", "General Discussion", "general"),
    ("conlanger", "Help Centre", "help"),
    ("conlanger", "Song Projects", "song-projects"),
    ("staff", "Staff Discussions", "discussions"),
)


def add_default_boards(apps, _):
    User = apps.get_model("cws2", "User")
    Group = apps.get_model("cws2", "Group")
    Board = apps.get_model("cws2", "Board")

    sheep = User.objects.get(username="sheep")
    groups = {
        "conlanger": Group.objects.get(slug="conlanger"),
        "staff": Group.objects.get(slug="staff"),
    }

    for board in BOARDS_TO_CREATE:
        Board.objects.create(
            group=groups[board[0]],
            name=board[1],
            slug=board[2],
            created_by=sheep,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('cws2', '0018_board_thread_post_board_cws2_board_unique_group_slug'),
    ]

    operations = [
        migrations.RunPython(add_default_boards, reverse_code=migrations.RunPython.noop),
    ]
